docs/management/start_stop.rst

Runserver will not work unless venv has been activated.

Fix path to server and add activation command

---

server/auvsi_suas/views/telemetry_test.py
server/server/settings.py

Enable the load tests by default and fix the telemetry load test, which
was missing an import.
Fixes #5

Enable and fix load tests

---

server/server/wsgi.py

When running on Vagrant, the interop repo (which contains the server
script) is shared with the guest via the synced_folders Vagrant config.
Unfortunately, this folder can be very slow, so the first request can
have significant latency, which is occasionally long enough to make
requests time out, and tests fail.
We already tell Apache to do some preloading, which preloads most of
Django, but Django itself lazily loads most of the modules needed to
service requests only when the first request arrives.
By sending a dummy request in the WSGI setup, we ensure that the first
real request has low latency.
Fixes #8

Force Django to import all necessary modules before first request

---

.travis.yml
README.md
setup/setup.sh

The config uses the exact same Puppet setup as a normal installation,
and runs the typical tests. It takes about 5 minutes to run.
In October, Travis finally added 14.04 as a base distro. My previous attempts to get our automated setup working on 12.04 were painful to say the least.

Add Travis CI config

---

server/requirements.txt

PyYAML is required for ``loaddata`` to be able to load our test fixture
into the database.
We were missing this dependency before, and simply relied on the system
having it installed by default.
Fixes #7

Install PyYAML for server

---

setup/.gitignore
setup/setup.sh

In addition to displaying setup output on the screen, redirect it to a
log file. This log will be helpful if teams need to upload setup output
for support.

Create a setup log file

---

server/auvsi_suas/admin.py

Certain models, such as GpsPosition and AerialPosition may have
thousands or hundreds of thousands of entries once a significant amount
of telemetry has been to the server.
By default, the admin interface will enumerate all options for these
ForeignKeys. This is infeasible when there are too many instances, so
just display a raw ID field instead. There will be a search button next
to the box, where a specific instance can be searched for or created.
References #13

Display raw ID fields for models with many instances

---

server/auvsi_suas/views/targets.py
server/auvsi_suas/views/targets_test.py

Currently, bad JSON results in an exception and 500 error to the client.

Verify that target requests are valid JSON

---

server/auvsi_suas/admin.py
server/auvsi_suas/fixtures/testdata/sample_mission.json
server/auvsi_suas/migrations/0011_remove_ir.py
server/auvsi_suas/models/mission_config.py
server/auvsi_suas/models/mission_config_test.py
server/auvsi_suas/static/auvsi_suas/components/mission-scene/mission-scene.js
server/auvsi_suas/views/auvsi_admin/live_kml_test.py
server/auvsi_suas/views/clear_cache_test.py
server/auvsi_suas/views/missions_test.py
server/auvsi_suas/views/obstacles_test.py
server/auvsi_suas/views/server_info_test.py
server/fixtures/test_fixture.yaml

The 2016 rules include no IR targets. Remove them from the
MissionConfig, KML, and frontend.
Fixes #21

Remove IR target positions

---

setup/puppet_files/auvsi_suas/manifests/base.pp

The virtualenv 14.0.1 package wheel creates a virtualenv-3.5 binary,
regardless of Python version. Since we are running Python 3.4, this
breaks later setup steps. By avoiding the wheel (and using the tar
instead), we avoid the issue.
See the virtualenv issue at pypa/virtualenv#851
(https://github.com/pypa/virtualenv/issues/851).
Fixes #26

Avoid the latest virtualenv wheel

---

docs/spec.rst

The docs are currently building with warnings because one HTTP
sourcecode block cannot be highlighted. The root cause is
sphinx-doc/sphinx#2280. Once that is fixed, the block should be fine as
previously written. Until then, explicitly add a Content-Type line to
avoid the bug.
Fixes #41

Work around sphinx-doc/sphinx#2280

---

docs/setup/machine_or_vm.rst
docs/setup/testing.rst
setup/README.md
setup/Vagrantfile
test.sh

Execute scripts with interpreter type.
For #28

Remove interpreter line execution to support Vagrant-Windows.

---

setup/puppet_files/auvsi_suas/manifests/base.pp

The latest version (1.11.0) of the stankevich-python Puppet module will
specify the appropriate version of Python to use to the system
virtualenv install. It is no longer necessary to use a separate
virtualenv installation for Python 3.
This is the recommended path forward from pypa/virtualenv#851, as the
versioned virtualenv binaries are likely going away.

Don't install virtualenv-3.4

---

server/auvsi_suas/migrations/0012_missionclockevent.py
server/auvsi_suas/models/__init__.py
server/auvsi_suas/models/mission_clock_event.py
server/auvsi_suas/models/mission_clock_event_test.py
server/auvsi_suas/models/takeoff_or_landing_event.py

For #45 
Following this PR:
1) Refactor [TakeoffOrLandingEvent.flights](https://github.com/auvsi-suas/interop/blob/master/server/auvsi_suas/models/takeoff_or_landing_event.py#L22) so generic implementation it is part of  [TimePeriod](https://github.com/auvsi-suas/interop/blob/master/server/auvsi_suas/models/time_period.py).
2) Refactor [TakeoffOrLandingEvent.user_in_air](https://github.com/auvsi-suas/interop/blob/master/server/auvsi_suas/models/takeoff_or_landing_event.py#L64) so it uses a function in `AccessLog` which gets the latest access log before a time. 
3) Add a method similar to `flights` and `user_in_air` to `MissionClockEvent` in order to get the on-mission-clock periods, on timeout periods, and whether the user is on mission clock / timeout.
4) Add grading of …

Add MissionClockEvent to track mission clock time.

---

client/interop/types.py
docs/spec.rst
server/auvsi_suas/models/uas_telemetry.py
server/auvsi_suas/views/telemetry.py

Explicitly state that the UAS telemetry heading and target orientation
are both based on true north, not magnetic north.
Closes #29

Heading and orientation reference true north

---

client/interop/types.py
client/interop/types_test.py
docs/spec.rst
server/auvsi_suas/migrations/0014_add_autonomous_targets.py
server/auvsi_suas/models/target.py
server/auvsi_suas/models/target_test.py
server/auvsi_suas/views/targets.py
server/auvsi_suas/views/targets_test.py

This field is used distinguish targets that are submitted as ADLC
targets. The rules are strict about only grading the first six
submissions, so these targets are locked down and may not be changed or
deleted once submitted.
References #30

Add 'autonomous' Target field

---

docs/requirements.txt

Sphinx 1.4 no longer includes it by default.

Add explicit sphinx_rtd_theme dependency

---

docs/conf.py
docs/requirements.txt
setup/puppet_files/auvsi_suas/manifests/docs_setup.pp

ReadTheDocs runs `pip install` from the root of the repo and doesn't
seem to be configurable, so it can't properly install the interop
client.
Instead of adding a dependency, teach Sphinx to mock the client
dependencies and import the module directly.

Drop interop client dependency from docs

---

setup/puppet_files/auvsi_suas/manifests/client_install.pp
setup/setup.sh

For some absurd reason, puppet exits with a zero exit code, even if the
configuration fails to apply. --detailed-exitcodes is needed to make it
exit non-zero:
https://docs.puppet.com/puppet/latest/reference/man/agent.html#OPTIONS
Now Travis builds should fail early when the configuration fails to
apply.

Make puppet exit with a non-zero code on failure

---

server/auvsi_suas/views/targets.py

Turns out for review we need an interface for requesting imagery. Rather than duplicate it, give admins access.

Allow admins ability to read targets+images.

---

server/auvsi_suas/views/targets.py
server/auvsi_suas/views/targets_test.py

Filter targets which don't have a thumbnail stored. Sort the final list
of targets by last edit time. This will provide a stable order for
reviewing.
Fixes #123

Review targets with image. Review in edit order.

---

server/auvsi_suas/static/auvsi_suas/app.css
server/auvsi_suas/static/auvsi_suas/app.js
server/auvsi_suas/static/auvsi_suas/auvsi_suas.conf.karma.js
server/auvsi_suas/static/auvsi_suas/components/backend/backend-service.js
server/auvsi_suas/static/auvsi_suas/components/backend/backend-service_test.js
server/auvsi_suas/static/auvsi_suas/components/navigation/navigation.js
server/auvsi_suas/static/auvsi_suas/pages/mission-dashboard/mission-dashboard.html
server/auvsi_suas/static/auvsi_suas/pages/target-review/target-review-controller.js
server/auvsi_suas/static/auvsi_suas/pages/target-review/target-review-controller_test.js
server/auvsi_suas/static/auvsi_suas/pages/target-review/target-review.css
server/auvsi_suas/static/auvsi_suas/pages/target-review/target-review.html
server/auvsi_suas/templates/auvsi_suas/index.html
server/auvsi_suas/views/targets.py
server/auvsi_suas/views/targets_test.py

Updates the backend review PUT to use the same field so it is directly
updatable by the Angular resource object.
Updates the menus for better organization of displays/tools. Updates the
help message on the dashboard.
Adds a new resource for target review requests. Adds a page to view
and update targets under review.
Fixes #54

Add a frontend for target review.

---

docs/management/configure_manage.rst
server/auvsi_suas/fixtures/testdata/sample_mission.json
server/auvsi_suas/models/distance.py
server/auvsi_suas/models/distance_test.py
server/auvsi_suas/models/mission_config.py
server/auvsi_suas/models/mission_config_test.py
server/auvsi_suas/models/units.py
server/auvsi_suas/models/units_test.py
server/auvsi_suas/views/missions_test.py
server/requirements.txt
server/server/settings.py
setup/puppet_files/auvsi_suas/manifests/server_install.pp

When evaluating waypoints, verify that every UAS telemetry point remains
within 100ft of the straight-line waypoint track.
To achieve this, we convert WGS84 coordinates into a cartesian
coordinate system (UTM), where we can do simply vector arithmetic to
determine the distance from the waypoint track line segment.
Fixes #71

Verify UAS remains along waypoint track

---

server/server/debug.py

New versions of Django give HTML responses with the content type
'text/html; charset: utf-8'. We don't want to wrap that, so only check
for a start of text/html.

Drop wrap content starting with text/html

---

server/auvsi_suas/fixtures/testdata/sample_mission.json
server/auvsi_suas/migrations/0018_accesslog.py
server/auvsi_suas/migrations/0019_accesslog_finish.py
server/auvsi_suas/models/access_log.py
server/auvsi_suas/models/access_log_test.py
server/auvsi_suas/models/server_info_access_log_test.py

Making AccessLog an abstract base class means that rather than having a
dedicated AccessLog table in the database, each subtype's table contains
the AccessLog fields.
In my stress test, this makes the SQL queries for `/api/teams` go from
taking 6600ms total to 120ms.
The change itself is trivial, but the migration is complex, as Django
cannot gracefully handle this kind of migration. See 0018_accesslog.py
for details.
References #139

Convert AccessLog to an abstract base class

---

server/server/settings.py

This gives a nice breakdown of where views are spending their time.
The max depth of 50 ensures we can actually see everything relevant.
References #139

Enable the profiling panel on the debug toolbar

---

client/interop/client_test.py
server/auvsi_suas/test_runner.py
server/requirements.txt
server/server/settings.py
setup/puppet_files/auvsi_suas/manifests/memcached_setup.pp
setup/puppet_files/auvsi_suas/manifests/server_setup.pp
setup/setup.sh

This will create a consistent cache, which removes need to repeatedly
press a cache invalidation button, allows us to do proper invalidation
in the future, and allows us to use the cache for recent event queries
(e.g. latest telemetry data per user).
For #143

Use Memcached over in-process cache.

---

server/auvsi_suas/models/mission_config.py
server/auvsi_suas/models/mission_config_test.py
server/auvsi_suas/views/missions_test.py

These IDs are internal implementation details not needed by the users of
the interface and provides unnecessary confusion.

Remove internal component ids within mission.

---

docs/specification.rst

Trailing commas are not allowed in JSON, and emergent_last_known_pos was
missing from GET /api/missions.

Cleanup spec sample JSON

---

server/auvsi_suas/fixtures/testdata/sample_mission.json
server/auvsi_suas/migrations/0023_index_together_user_timestamp.py
server/auvsi_suas/models/access_log.py
server/auvsi_suas/models/access_log_test.py
server/auvsi_suas/models/mission_clock_event.py
server/auvsi_suas/models/mission_config_test.py
server/auvsi_suas/models/takeoff_or_landing_event.py
server/auvsi_suas/models/uas_telemetry.py
server/auvsi_suas/static/auvsi_suas/components/team-status/team-status-controller.js
server/auvsi_suas/static/auvsi_suas/components/team-status/team-status-controller_test.js
server/auvsi_suas/static/auvsi_suas/components/team-status/team-status.html
server/auvsi_suas/static/auvsi_suas/pages/mission-dashboard/mission-dashboard-controller.js
server/auvsi_suas/static/auvsi_suas/pages/mission-dashboard/mission-dashboard-controller_test.js
server/auvsi_suas/static/auvsi_suas/pages/mission-dashboard/mission-dashboard.html
server/auvsi_suas/views/teams.py
server/auvsi_suas/views/teams_test.py

Returning telemetry in the teams request makes fewer requests and
database queries.
Indexing (user,timestamp) should allow simultaneous user filtering,
timestamp filtering, and ordering by timestamp via the index without
having to post-filter and post-sort. This should make requests more
efficient.
Fixes #164

Return telemetry in teams request. Index (user,timestamp) for telemetry.

---

server/auvsi_suas/fixtures/testdata/sample_mission.json
server/auvsi_suas/models/mission_config.py
server/auvsi_suas/models/mission_config_test.py
server/auvsi_suas/models/target.py
server/auvsi_suas/models/target_test.py
server/server/settings.py

* Update match_value function to take into account new scoring scheme
* Update location scoring to be linear
* Update classification scoring 
* Update actionable scoring such that target is only actionable if it is submitted during first flight. Remove classification/location requirements for actionable targets
* Add `interop_submission` field to target to keep track of whether the target was submitted via the interop system. A target is marked as being submitted via the interop system if it is uploaded/updated while the team is still on mission clock. (Any targets uploaded/updated after then are probably a judge uploading from USB submission)
* Change weighting of location, classification and actionable scores. Take into account interop score and autonomy score when calculating match …

Update target scoring

---

tools/requirements.txt
tools/setup_tools.sh

Appears that urllib3+requests has become a new dependency as builds have been
failing with:
Could not import extension sphinx.builders.linkcheck (exception: No
module named packages.urllib3.exceptions)

Add urllib3+requests to tools requirements for docs build.

---

client/interop/types.py
client/interop/types_test.py
client/tools/interop_cli.py
client/tools/upload_targets.py
server/auvsi_suas/views/targets.py
server/auvsi_suas/views/targets_test.py

It will allow an admin user to create a target on behalf of a team. This change is a prereq to adding an `actionable_override` flag.

Add a team_id field to targets POST

---

.travis.yml
client/tools/interop_cli.py

For high-rate telemetry forwarding, we don't want to print urllib debug messages.
Sleeping will reduce flakiness of client test and spurious build errors.

Set default logging to INFO. Sleep before client test.

---

.travis.yml
server/Dockerfile
server/run.sh

Purpose is to decrease sporatic CI test failures because the client
tests start before the server is ready. Secondary benefit to increase
health status visibility via a secondary prober.
Healthcheck which will probe the Docker container to validate that the
server is healthy. It simply polls the homepage (/) using curl. It
stores the status and any errors, and can be queried using `docker
inspect`. Format is defined here:
https://docs.docker.com/engine/reference/builder/#/healthcheck

Add healthcheck to container, poll in Travis.

---

server/auvsi_suas/models/fly_zone.py
server/auvsi_suas/models/fly_zone_test.py
server/auvsi_suas/models/mission_config.py
server/auvsi_suas/models/mission_config_test.py
server/auvsi_suas/views/auvsi_admin/evaluate_teams.py
server/auvsi_suas/views/auvsi_admin/evaluate_teams_test.py

This is in prep for adding more evaluation data that will be exported
(e.g. total mission score), and for a more complex export which will
include json (post-analysis), csv (downstream scoring), and tex (team
feedback).
For #218

Refactor evaluation data into object.

---

server/auvsi_suas/static/auvsi_suas/pages/evaluate-teams/evaluate-teams-controller.js
server/auvsi_suas/static/auvsi_suas/pages/evaluate-teams/evaluate-teams-controller_test.js
server/auvsi_suas/static/auvsi_suas/pages/evaluate-teams/evaluate-teams.html
server/auvsi_suas/views/auvsi_admin/evaluate_teams.py
server/auvsi_suas/views/auvsi_admin/evaluate_teams_test.py
server/auvsi_suas/views/urls.py

A single zip file makes it more efficient to get both json and csv back
at the same time (csv for higher-level scoring, json for team feedback).
Per team json makes creating a single PDF for feedback easier as it
doesn't require parsing the json to break out by team.
For #218

Return csv/json team evaluations as single zip.

---

client/interop/client.py

This is to decrease test flakiness. At competition, it'd be better to
wait up to 10s and succeed rather than failing. Add up to 10 retries to
establish a connection with the server.

Increase client timeouts to 10s. Add conn retries.

---

server/auvsi_suas/migrations/0027_target_description_approved.py
server/auvsi_suas/models/target.py
server/auvsi_suas/models/target_test.py
server/auvsi_suas/proto/target.proto
server/auvsi_suas/static/auvsi_suas/pages/target-review/target-review-controller.js
server/auvsi_suas/static/auvsi_suas/pages/target-review/target-review-controller_test.js
server/auvsi_suas/static/auvsi_suas/pages/target-review/target-review.css
server/auvsi_suas/static/auvsi_suas/pages/target-review/target-review.html
server/auvsi_suas/views/targets.py
server/auvsi_suas/views/targets_test.py

This adds a field as to whether the emergent description is approved by
the judge. It updates scoring of the emergent target to use this field
when calculating the classification score. It also updates scoring to
give zero value to an image without an approved thumbnail.
Fixes #228

Add description_approval field. Update scoring.

---

server/auvsi_suas/views/targets.py

Currently a request body which is valid JSON but doesn't convert to a
Python dict will cause a TypeError and return 500. Return a 400 error
instead.
Fixes #237
Sans-comments, will submit tomorrow morning.
@foochuanwei FYI

Return 400 on invalid request, rather than 500.

---

server/auvsi_suas/models/access_log.py
server/auvsi_suas/models/mission_evaluation.py
server/auvsi_suas/models/mission_evaluation_test.py
server/auvsi_suas/proto/mission.proto
server/server/settings.py

Respect the telemetry prerequisite requiring teams to have at least a
1Hz rate of telemetry to get points for waypoint accuracy or for
obstacle avoidance.
Adds scoring of obstacle avoidance.
For #218
As the milestone deadline is approaching, I'm going to submit tomorrow morning sans comments.

Respect telem prereq. Score obstacle avoidance.

---

docs/specification.rst

Simplifies interface and implementation compared to special-casing off
axis having a known position. This is what the server has been doing so
far.
Fixes #257

Require lat/lon for off axis.

---

server/auvsi_suas/models/mission_evaluation_test.py
server/server/settings.py

Reduce manual takeover penalty from 25% to 10%.
Reduce out of bounds penalty from 20% to 10%.
Reduce safety bounds penalty from 100% total to 10% additional
For #264

Update penalty weights for takeover and bounds.

---

.travis.yml
server/Dockerfile
server/healthcheck.py
server/requirements.txt
server/run.sh

Use it to check for postgres health prior to trying to insert data into
the postgres database. Use it instead of flaky and slower-than-needed
sleep calls.
Fixes #273

Create more granular health check.

---

server/auvsi_suas/models/mission_evaluation.py
server/auvsi_suas/models/mission_evaluation_test.py
server/auvsi_suas/models/odlc.py
server/auvsi_suas/models/odlc_test.py
server/auvsi_suas/proto/mission.proto
server/auvsi_suas/proto/odlc.proto
server/server/settings.py

SUAS 2018 rules changed to require interop submission instead of giving
points for it. Geolocation and actionable absorbed those points.
For #286

Remove interop submit points. Update odlc weights.

---

server/auvsi_suas/models/mission_evaluation.py
server/auvsi_suas/models/mission_evaluation_test.py

Negative total scores aren't desired as team which flies shouldn't do
worse than team which doesn't show up to competition. Interop returning
a negative value required post processing before integration with total
score sheets.
For #271

Lower bound mission score by 0 for high penalty.

---

server/auvsi_suas/models/mission_config.py
server/auvsi_suas/models/mission_config_test.py
server/auvsi_suas/models/moving_obstacle.py
server/auvsi_suas/models/moving_obstacle_test.py
server/auvsi_suas/models/stationary_obstacle.py
server/auvsi_suas/models/stationary_obstacle_test.py
server/auvsi_suas/models/uas_telemetry.py
server/auvsi_suas/models/uas_telemetry_test.py
server/auvsi_suas/views/auvsi_admin/export_kml.py
server/auvsi_suas/views/auvsi_admin/live_kml.py
server/server/settings.py

Waypoints were from telemetry line to point and stationary obstacles
were based on calculated intersection with cylinder. Moving obstacles
calculation should not have changed.
Fixes bug where stationary obstacle collision doesn't handle case where
line intersection does not imply line segment intersection. Adds
regression test case for such.
Refactors KML to prevent circular dependency. Moving obstacles now
render their own KML folder and aren't tied to teams. To save dev time
in this time-constrained moment, removed proximity markup for KML and
added a TODO note to put it back as part of #311.
Tested with sample data provided in #316 and verified correct reporting
of stationary hits. Note that it appears interpolation of moving
obstacles has changed slightly, as obstacle 3 now reports …

Unify interpolation on discrete telemetry interp.

---

.travis.yml

This should move us to the default Travis environment, which is
containerized and improves performance/boot-time.
For #322

Remove sudo requirement from Travis.

---

.travis.yml
tools/deploy.sh

Allows teams to upgrade server versions when desired and not always when
there's a git push.
Fixes #339

Tag the Docker image with date during deploy.

---

server/auvsi_suas/models/mission_evaluation.py
server/auvsi_suas/models/mission_evaluation_test.py
server/auvsi_suas/proto/mission.proto
server/auvsi_suas/views/auvsi_admin/evaluate_teams_test.py

Simplifies the code base and removes confusion from conflicting interop
analysis and judge feedback.
Out of bounds is noisy due to handling of takeoff/landing regions, and
prevents us from having to create extra fly zones covering the area
around the takeoff zone which confused teams.
Mission time is perfectly accurate at the lead judge (e.g. sees the team
enter/leave runway), but interop operator usually gets delayed
information, usually leading to conflicting values.
Fixes #343

Remove analysis not used in scoring.

---

server/auvsi_suas/models/access_log.py

This allows operators to override the timestamp via the Django admin
display, an operation which might be necessary to correct
TakeoffOrLandingEvent times. Sets now() as the default time in the
constructor, mimicing the behavior for the rest of the code.
Fixes #350

Drop auto_now_add for AccessLog.

---

server/server/settings.py

The New York timezone is the competition timezone. This will make admin
displays which show times intuitive (e.g. Django admin page for
TakeoffOrLandingEvent). UTC is unlikely to be a better default for
display. Django always stores datetime as UTC in the database.

Set the server timezone to New York.

---

client/Dockerfile
client/setup.py
client/test.sh

Improves local testing experience (doesn't litter build files) and improves testing coverage.

Use setup.py to configure client container.

---

client/auvsi_suas/client/client.py
client/auvsi_suas/client/client_test.py
client/tools/interop_cli.py
client/tools/interop_cli_test.py
server/auvsi_suas/views/missions.py
server/auvsi_suas/views/missions_test.py

Updates API to get all missions to be admin only, requiring all teams to
specify the mission ID to request details. The competition is moving to
multiple simultaneous missions, so now the list of missions may have
more than one. To prevent likely bugs like always selecting the first in
the list, we force teams to provide the ID of their mission.
Updates client library and CLI to reflect this change.
Fixes #379

Require mission ID in request for mission details.

---

server/auvsi_suas/frontend/pages/odlc-review-controller.js

Testing our integration with the new proto-based api, I was afraid we did something wrong when I checked the ODLC review screen and saw no shape color:
Turns out the issue was actually with the interop server.

Fix missing shape color field on ODLC review.

---

proto/interop_admin_api.proto
server/auvsi_suas/frontend/pages/evaluate-teams.html
server/auvsi_suas/frontend/pages/mission-dashboard-controller.js
server/auvsi_suas/views/teams.py
server/auvsi_suas/views/teams_test.py

Single team eval was broken by the proto change when field names were
changed. This fixes the field naming and adds back the id field.
Fixes a performance issue in the dashboard where intervals weren't
stopped on page change and new intervals would be created on navigation
back. This would cause N intervals to be running, growing load on the
server by N times. Now the controller listens for destroy and cancels
the interval.

Fix single-team eval field names. Fix dash perf.

---

proto/interop_admin_api.proto
server/auvsi_suas/models/mission_evaluation.py
server/auvsi_suas/models/mission_evaluation_test.py

This makes the penalty structure parallel, rather than having a special
case for scoring takeovers. This was part of a rule update mid-year.
Also increases the weighting of manual flight takeovers.
Fixes #382

Make safety pilot takeover a section level penalty.

---

server/auvsi_suas/views/odlcs.py
server/auvsi_suas/views/odlcs_test.py

Detects when the mission ID for an ODLC submission doesn't correspond to
a valid mission.

Return HTTP 400 rather than 500 for wrong mission.

---

server/auvsi_suas/models/aerial_position.py
server/auvsi_suas/models/aerial_position_test.py
server/auvsi_suas/models/fly_zone.py
server/auvsi_suas/models/fly_zone_test.py
server/auvsi_suas/models/gps_position.py
server/auvsi_suas/models/gps_position_test.py
server/auvsi_suas/models/mission_config.py
server/auvsi_suas/models/mission_config_test.py
server/auvsi_suas/models/mission_judge_feedback.py
server/auvsi_suas/models/mission_judge_feedback_test.py
server/auvsi_suas/models/odlc.py
server/auvsi_suas/models/stationary_obstacle.py
server/auvsi_suas/models/stationary_obstacle_test.py
server/auvsi_suas/models/takeoff_or_landing_event.py
server/auvsi_suas/models/uas_telemetry.py
server/auvsi_suas/models/uas_telemetry_test.py
server/auvsi_suas/models/waypoint.py

Validates fields using Django's field validator and clean() model
method. This ensures validity of objects created via the administration
form. This does not validate in instances where save() is called, which
is already covered by view code.
Note this does not validate any many-to-many field, a limitation of
Django's framework which cannot access those fields before saving. In
practice, this only limits the min/max count tests (enough points to
define a fly zone polygon, not too many stationary obstacles) and the
max-distance waypoint test.
We'll need a view to handle more advanced validation. For now, this will
suffice.
Fixes #378

Add basic db validation of fields.

---

server/auvsi_suas/views/odlcs.py
server/auvsi_suas/views/odlcs_test.py

This will prevent teams with bugs from uploading 10000s of ODLCs and
making ODLC review near impossible.
Fixes #323

Limit ODLC to max in rules plus small buffer.

---

proto/interop_admin_api.proto
server/auvsi_suas/frontend/app.js
server/auvsi_suas/frontend/components/navigation.js
server/auvsi_suas/frontend/pages/gps-conversion-controller.js
server/auvsi_suas/frontend/pages/gps-conversion.html
server/auvsi_suas/views/urls.py
server/auvsi_suas/views/utils.py
server/auvsi_suas/views/utils_test.py
server/config/requirements.txt
server/server/settings.py

Many of the mission parameters are determined using the string format of
GPS rather than the decimal format. Previously an offline CLI was used
to perform this conversion. To save the interop operator from knowing
how to use a command line and CLI, this pushes it into the web
interface.
For #315

Add GPS conversion utility page.

---

server/auvsi_suas/models/mission_config.py

There is a circular reference between MissionConfig and Odlc. This will
enable a mission to be created without ODLCs, so that ODLCs can then be
created, followed by assigning the ODLCs to the MissionConfig.
Fixes #426

Add blank=True to MissionConfig.odlcs.

---

server/config/nginx.conf

Scoring may take longer than the default timeout.
For #427.

Set uwsgi_read_timeout to 10min.

---

server/auvsi_suas/models/access_log.py
server/auvsi_suas/models/access_log_test.py
server/auvsi_suas/models/mission_evaluation_test.py
server/auvsi_suas/models/uas_telemetry.py
server/auvsi_suas/models/uas_telemetry_test.py
server/auvsi_suas/views/missions.py

Fixes rate calculation that had an off-by-one error while indexing into
the logs which caused it to not include the measurement between the last
two logs.
Improves rate calculation and telemetry deduping to leverage iterator
rather than materializing as lists (loading all data into memory at
once).
Fixes KML output to only emit logs for the flight periods, not for all
of time.

Fix rate calculation. Fix KML output.

---

README.md
client/auvsi_suas/client/client.py
client/auvsi_suas/client/client_test.py
client/tools/interop_cli.py
client/tools/interop_cli_test.py
proto/interop_admin_api.proto
proto/interop_api.proto
server/auvsi_suas/views/teams.py
server/auvsi_suas/views/teams_test.py

Makes the endpoint /api/teams public so that teams can use it for moving
obstacle avoidance.
Adds telemetry age so teams can extrapolate where the UAS is currently.
Adds telemetry ID so teams can dedupe the same telemetry message which
might otherwise indicate the UAS isn't moving.
Adds to the CLI so it's convenient for teams to access.
Fixes #450

Make /api/teams public. Add age & ID. Add to CLI.

---

proto/interop_admin_api.proto
server/auvsi_suas/models/mission_evaluation.py
server/auvsi_suas/models/mission_evaluation_test.py
server/auvsi_suas/views/missions_test.py
tools/format.sh

Filtering inactive users will make it possible to merge multi-mission
evaluations by catting the result.
Adds mission ID to the eval output so that state is maintained post
merging the outputs.
Fixes #448

Filter inactive users. Add mission to eval.

---

server/docker-compose.yml
server/interop-server.sh
server/server/settings.py

A minor version upgrade made a backwards-incompatible change which broke
CI/CD and competitor use of server image. Pins the postgres image to a
specific version to prevent this from happening in the future.
Sets the username and password for the database superuser account, which
is now required to connect. Note for security this is preferrable to
POSTGRES_HOST_AUTH_METHOD, which would accept any connection that can
access the port, as we can change the password at competition to lockout
teams, similar to how we change the session tokens.
Fixes #470.

Pin postgres version. Set postgres user/pass.

---

client/setup.py

I found some issues with the subpackages (client, proto) not being properly installed with `python setup.py install`. Switching the hardcoded `packages=['auvsi-suas']`to setuptools.find_packages() fixes this, and nevertheless is good practice anyway!

Switch hardcoded packages to find_packages()

---

client/configure.sh
client/interop-client.sh
server/interop-server.sh
tools/deploy.sh
tools/format.sh
tools/setup_tools.sh

`interop-server.sh` doesn't run on NixOS (and I think probably not Mac but I can't confirm) because of the shebang being `#!/bin/bash` instead of `#!/usr/bin/env bash`. This switches all scripts' shebangs to use `/usr/bin/env`.

Use /usr/bin/env in all shebangs

---

client/requirements.txt

Upgrade version to support Python 3.9.
Fixes #490.

Upgrade pymavlink to 2.4.14.
