README.md

It currently just links to the image.

Make documentation badge link to docs

---

docs/setup/testing.rst

Explain the new testing script and output format.
This supersedes #1.

Update testing docs

---

docs/setup/downloading.rst
docs/setup/machine_or_vm.rst
docs/setup/vagrant.rst

Grepped for auvsi_suas_competition and fixed all instances found.

Update paths in docs to reflect current pathnames

---

docs/management/configure_manage.rst
docs/management/debugging.rst
docs/management/start_stop.rst
docs/setup/machine_or_vm.rst
docs/setup/testing.rst
docs/setup/vagrant.rst

Several parts of the documentation are out-of-date and incorrect.
Correct them.
There is also some missing information, such as the default username and
password to document,

Documentation update

---

server/auvsi_suas/views/middleware.py
server/server/settings.py

Add logging middleware. Configure logging.

---

docs/spec.rst
server/auvsi_suas/models/target.py

Update rule refs and remove IR target type.

---

client/interop/__init__.py
client/interop/types.py
client/interop/types_test.py

Add Target to the interop client types.

---

client/interop/types.py
client/interop/types_test.py

Add id,user to Target. Change target_type to type.

---

client/interop/client.py
client/interop/client_test.py
client/interop/types.py
client/interop/types_test.py

Replacement for PR #52 
For #44

Remove client side validation. Add deserialize method.

---

client/interop/client.py
client/interop/client_test.py
client/interop/types.py
client/interop/types_test.py

Add target endpoints to client.

---

server/auvsi_suas/models/access_log.py
server/auvsi_suas/models/access_log_test.py
server/auvsi_suas/models/mission_clock_event.py
server/auvsi_suas/models/mission_clock_event_test.py
server/auvsi_suas/models/takeoff_or_landing_event.py

Refactor inair into AccessLog. Add user on mission/timeout.

---

server/auvsi_suas/models/mission_clock_event.py
server/auvsi_suas/models/mission_clock_event_test.py
server/auvsi_suas/models/takeoff_or_landing_event.py
server/auvsi_suas/models/time_period.py
server/auvsi_suas/models/time_period_test.py

Refactor time periods from flights. Add time periods to clock.

---

setup/puppet_files/auvsi_suas/manifests/server_install.pp
setup/setup.sh

Use puppet npm installer instead of command.

---

server/auvsi_suas/models/fly_zone.py
server/auvsi_suas/models/mission_config.py
server/auvsi_suas/models/moving_obstacle.py
server/auvsi_suas/models/uas_telemetry.py
server/auvsi_suas/models/uas_telemetry_test.py
server/auvsi_suas/models/units.py
server/auvsi_suas/models/units_test.py
server/auvsi_suas/views/auvsi_admin/export_kml_test.py

Use meters as altitude format for KML.

---

server/auvsi_suas/models/mission_clock_event.py
server/auvsi_suas/views/teams.py
server/auvsi_suas/views/teams_test.py

Get/Put whether on_mission,on_timeout in user_json.

---

server/auvsi_suas/admin.py
server/auvsi_suas/fixtures/testdata/sample_mission.json
server/auvsi_suas/models/mission_config.py
server/auvsi_suas/models/mission_config_test.py
server/auvsi_suas/models/time_period.py
server/auvsi_suas/models/time_period_test.py
server/auvsi_suas/views/auvsi_admin/evaluate_teams.py

Add grading of mission clock.

---

server/auvsi_suas/static/auvsi_suas/auvsi_suas.conf.karma.js
server/auvsi_suas/static/auvsi_suas/components/team-status/team-status-controller.js
server/auvsi_suas/static/auvsi_suas/components/team-status/team-status-controller_test.js
server/auvsi_suas/static/auvsi_suas/components/team-status/team-status.css
server/auvsi_suas/static/auvsi_suas/components/team-status/team-status.html
server/auvsi_suas/static/auvsi_suas/pages/mission-dashboard/mission-dashboard-controller.js
server/auvsi_suas/static/auvsi_suas/pages/mission-dashboard/mission-dashboard-controller_test.js
server/auvsi_suas/static/auvsi_suas/pages/mission-dashboard/mission-dashboard.css
server/auvsi_suas/static/auvsi_suas/pages/mission-dashboard/mission-dashboard.html
server/auvsi_suas/templates/auvsi_suas/index.html

Refactor team status into directive. Show on_clock/timeout.

---

setup/setup.sh

Specify puppet stdlib to be added & upgraded.

---

server/auvsi_suas/migrations/0015_target_thumbnail_approved.py
server/auvsi_suas/models/target.py

Add field for judges to approve thumbnails for grading.

---

client/missionplanner/clientproxy.py

* Mark arguments as required
* Support Python 3
Fixes #85

Mission Planner script improvements

---

docs/integration/mission_planner.rst

These aren't very detailed, but they are a quick start.
Related to #83

Add basic Mission Planner docs

---

client/interop/client.py

Note that Client handles authentication cookie

---

client/targets/README.md
client/targets/upload_targets.py
client/testdata/targets.txt
server/auvsi_suas/views/urls.py
server/server/settings.py

Fixes #53 
Added MEDIA_URL as well so that in debug mode you can view the target images in the admin display. Note that Django doesn't let MEDIA_URL run in non-debug mode (no security on image access).

Add target upload tool.

---

docs/conf.py
docs/integration/client.rst
docs/requirements.txt
setup/puppet_files/auvsi_suas/manifests/docs_setup.pp

Add auto-generated interop client docs.

---

server/auvsi_suas/static/auvsi_suas/test_with_phantomjs.sh
setup/puppet_files/auvsi_suas/manifests/base.pp
setup/puppet_files/auvsi_suas/manifests/server_install.pp
setup/setup.sh

Use puppet 4.x via puppetlab's repo. Install npm via puppet.

---

server/auvsi_suas/migrations/0016_add_target_time.py
server/auvsi_suas/models/target.py
server/auvsi_suas/models/target_test.py

Add creation and last modified time to Target

---

server/auvsi_suas/migrations/0016_missionconfig_targets.py
server/auvsi_suas/migrations/0017_missionconfig_targets.py
server/auvsi_suas/models/mission_config.py
server/auvsi_suas/models/target.py
server/auvsi_suas/models/target_test.py
server/auvsi_suas/views/targets.py
server/requirements.txt
server/server/settings.py

For #55
Note, after #31 we will have to add in a field for actionable.

Add automatic evaluation of submitted targets.

---

server/auvsi_suas/models/target.py
server/auvsi_suas/models/target_test.py
server/auvsi_suas/views/targets.py

Provide more details to admins.

---

server/auvsi_suas/fixtures/testdata/sample_mission.json
server/auvsi_suas/models/mission_config_test.py
server/auvsi_suas/models/target.py
server/auvsi_suas/models/target_test.py
server/server/settings.py

Score objective/threshold level of actionable intelligence and include
the result in the evaluation dict. No scores are used at this point,
simply an objective/threshold string.
sample_mission.json is unchanged expect for the addition of real and
submitted targets. Unfortunately the database dump reordered the file.
References #31

Actionable Intelligence scoring

---

server/server/settings.py

This allows it to work offline.

Use local copy of jQuery for debug toolbar

---

server/auvsi_suas/models/mission_config.py
server/auvsi_suas/models/mission_config_test.py

Include the closest approach to each waypoint along the waypoint path.
Only the waypoints that are hit, plus the final one they did not hit are
included.

Evaluate closest approach to targets

---

setup/puppet_files/auvsi_suas/manifests/postgresql_setup.pp

Add memory for sort operations.

---

setup/setup.sh

Remove unnecessary upgrade from automated setup.

---

.travis.yml
docs/setup/machine_or_vm.rst
setup/setup.sh

Remove sudo from setup script, require it externally.

---

server/auvsi_suas/admin.py
server/auvsi_suas/fixtures/testdata/sample_mission.json
server/auvsi_suas/migrations/0021_remove_obstacle_log.py
server/auvsi_suas/models/__init__.py
server/auvsi_suas/models/mission_config.py
server/auvsi_suas/models/mission_config_test.py
server/auvsi_suas/models/obstacle_access_log.py
server/auvsi_suas/models/obstacle_access_log_test.py
server/auvsi_suas/views/auvsi_admin/evaluate_teams_test.py
server/auvsi_suas/views/obstacles.py
server/auvsi_suas/views/obstacles_test.py

Remove obstacle access log.

---

server/auvsi_suas/static/auvsi_suas/components/team-status/team-status-controller.js
server/auvsi_suas/static/auvsi_suas/components/team-status/team-status.css
server/auvsi_suas/static/auvsi_suas/components/team-status/team-status.html
server/auvsi_suas/static/auvsi_suas/pages/mission-dashboard/mission-dashboard-controller.js
server/auvsi_suas/static/auvsi_suas/pages/mission-dashboard/mission-dashboard.html

Add telemetry to dashboard. Use icons on dashboard.

---

server/auvsi_suas/models/mission_config.py
server/auvsi_suas/models/mission_config_test.py
server/auvsi_suas/views/missions.py
server/auvsi_suas/views/missions_test.py
server/auvsi_suas/views/urls.py

Add interface to request mission details.

---

docs/spec.rst

Updated docs to add mission API and remove server info.

---

client/interop/client.py
client/interop/client_test.py

Add mission request to client.

---

client/tools/README.md
client/tools/get_missions.py
client/tools/upload_targets.py

Add tool to request mission details and print them.

---

client/tools/README.md
client/tools/prober.py

It used a different program structure and argument names.

Cleanup prober to be similar to other tools.

---

docs/client.rst
docs/configuration.rst
server/auvsi_suas/models/access_log.py
server/auvsi_suas/models/aerial_position.py
server/auvsi_suas/models/fly_zone.py
server/auvsi_suas/models/gps_position.py
server/auvsi_suas/models/mission_clock_event.py
server/auvsi_suas/models/mission_config.py
server/auvsi_suas/models/moving_obstacle.py
server/auvsi_suas/models/stationary_obstacle.py
server/auvsi_suas/models/takeoff_or_landing_event.py
server/auvsi_suas/models/target.py
server/auvsi_suas/models/uas_telemetry.py
server/auvsi_suas/models/waypoint.py

Add sphinx class docs to configuration.

---

client/interop/types.py
client/interop/types_test.py
client/tools/get_missions.py

Make mission serializable. Use pretty print in get_missions.

---

docs/getting_started.rst

These were missed when converting from dot to dash.

Fix docker image name references

---

server/auvsi_suas/views/auvsi_admin/evaluate_teams.py
server/auvsi_suas/views/auvsi_admin/evaluate_teams_test.py
server/auvsi_suas/views/urls.py

Add ability to request eval as JSON.

---

client/interop/types.py
client/interop/types_test.py
docs/specification.rst
server/auvsi_suas/admin.py
server/auvsi_suas/fixtures/testdata/sample_mission.json
server/auvsi_suas/migrations/0022_remove_missionconfig_sric_pos.py
server/auvsi_suas/models/mission_config.py
server/auvsi_suas/models/mission_config_test.py
server/auvsi_suas/static/auvsi_suas/components/mission-scene/mission-scene.js
server/auvsi_suas/views/auvsi_admin/live_kml_test.py
server/auvsi_suas/views/clear_cache_test.py
server/auvsi_suas/views/missions_test.py
server/auvsi_suas/views/obstacles_test.py
server/fixtures/test_fixture.yaml

Remove SRIC.

---

server/auvsi_suas/models/mission_config.py
server/auvsi_suas/models/mission_config_test.py
server/auvsi_suas/views/auvsi_admin/evaluate_teams.py
server/auvsi_suas/views/auvsi_admin/evaluate_teams_test.py

Add specific-team eval output.

---

client/interop/types.py
client/interop/types_test.py
docs/specification.rst
server/auvsi_suas/models/mission_config.py
server/auvsi_suas/models/mission_config_test.py
server/auvsi_suas/views/missions_test.py

Expose emergent target in mission interface.

---

client/tools/interop_cli.py
client/tools/upload_targets.py

There are two commits in this PR. The first adds support for uploading via the 2017 object file format. The second adds a helpful mode that fetches the uploaded targets.

Update upload tool

---

docs/getting_started.rst

Update docs to reference new target upload.

---

server/auvsi_suas/views/missions.py
server/auvsi_suas/views/missions_test.py

JsonResponse wasn't actually imported, so attempting to use
GET /api/missions/ID resulted in a 500 error.
Add tests for this view.
Fixes #193

Fix GET /api/missions/ID

---

server/auvsi_suas/static/auvsi_suas/app.js
server/auvsi_suas/static/auvsi_suas/auvsi_suas.conf.karma.js
server/auvsi_suas/static/auvsi_suas/components/navigation/navigation.js
server/auvsi_suas/static/auvsi_suas/pages/evaluate-teams/evaluate-teams-controller.js
server/auvsi_suas/static/auvsi_suas/pages/evaluate-teams/evaluate-teams-controller_test.js
server/auvsi_suas/static/auvsi_suas/pages/evaluate-teams/evaluate-teams.css
server/auvsi_suas/static/auvsi_suas/pages/evaluate-teams/evaluate-teams.html
server/auvsi_suas/static/auvsi_suas/pages/mission-dashboard/mission-dashboard-controller.js
server/auvsi_suas/templates/auvsi_suas/index.html

Fixes #145 
Diff-based with branch `inter-refactor`.

Add page to evaluate teams.

---

docs/automation.rst
docs/getting_started.rst
docs/index.rst

Add doc on local Python access for automation.

---

server/auvsi_suas/models/mission_config.py
server/auvsi_suas/models/mission_config_test.py
server/server/settings.py

* Score waypoints using formula `max(0, (100ft -distance) / 100ft)`
* Report scores for best sequence
* Report closest approach to waypoints
* Update tests

Update waypoint scoring

---

server/auvsi_suas/models/fly_zone.py
server/auvsi_suas/models/fly_zone_test.py
server/auvsi_suas/models/mission_config.py
server/auvsi_suas/models/mission_config_test.py
server/server/settings.py

Report number of times team went out of bounds.
Fixes #173

Boundary violations

---

server/auvsi_suas/admin.py
server/auvsi_suas/migrations/0026_mission_judge_feedback.py
server/auvsi_suas/models/mission_judge_feedback.py

This will be used to automatically score the entire mission, which
includes manual judge-graded elements.
Based on rules which can be found here:
www.auvsi-suas.org/static/competitions/2017/auvsi_suas-2017-rules.pdf
For #218

Create model to hold mission feedback by judges.

---

server/fixtures/test_fixture.yaml

Make test fixture valid.

---

server/auvsi_suas/models/mission_evaluation.py
server/auvsi_suas/models/mission_evaluation_test.py
server/server/settings.py

Add auto timeline scoring to evaluation.

---

server/auvsi_suas/models/mission_evaluation_test.py

For #218 
Sans-comments, will submit Thursday morning.

Add additional tests for timeline scoring.

---

server/auvsi_suas/models/distance_test.py
server/auvsi_suas/models/mission_evaluation.py
server/auvsi_suas/models/mission_evaluation_test.py
server/auvsi_suas/proto/mission.proto
server/server/settings.py

Add auto scoring of autonomous flight.

---

server/auvsi_suas/models/mission_evaluation.py
server/auvsi_suas/models/mission_evaluation_test.py
server/auvsi_suas/models/target.py
server/auvsi_suas/models/target_test.py

For #218
Given the approaching milestone deadline, I will submit tomorrow morning sans comments.

Add object scoring to evaluation.

---

server/auvsi_suas/models/uas_telemetry.py
server/auvsi_suas/models/uas_telemetry_test.py
server/server/settings.py

Implement linear + spline interpolation for waypoints. Spline interpolation takes a really long time to run, so I would appreciate any advice.

Waypoint interpolation

---

server/auvsi_suas/models/uas_telemetry.py
server/auvsi_suas/models/uas_telemetry_test.py

In previous rules, you had to travel within 100ft and it was assumed
that you couldn't skip between waypoints as a result. In the new rules,
the constraint is only that they waypoint hits used must be in sequence,
and the max scoring sequence is used.
This new approach uses dynamic programming to find the best sequence. It
first filters the telemetry logs for the hits (much fewer) and then
calculates the max-scoring sequence recurrence.
Fixes #250

Update waypoint scoring to 2017 rules.

---

server/auvsi_suas/models/distance.py
server/auvsi_suas/models/stationary_obstacle.py
server/auvsi_suas/models/stationary_obstacle_test.py

For #260 
Got rid of extrapolation as discussed the telemetry rate requirement will take care of it.

Interpolation for stationary obstacles.

---

server/auvsi_suas/models/moving_obstacle.py
server/auvsi_suas/models/moving_obstacle_test.py
server/server/settings.py

Interpolation for moving obstacles

---

server/auvsi_suas/fixtures/testdata/sample_mission.json
server/auvsi_suas/migrations/0030_crash_tfoa.py
server/auvsi_suas/models/mission_evaluation.py
server/auvsi_suas/models/mission_evaluation_test.py
server/auvsi_suas/models/mission_judge_feedback.py
server/auvsi_suas/models/mission_judge_feedback_test.py
server/auvsi_suas/proto/mission.proto
server/server/settings.py

Add TFOA and crash penalties.

---

tools/setup_tools.sh

Install tools requirements into venv.

---

server/auvsi_suas/admin.py
server/healthcheck.py

Improve psgl healthcheck. Use horizontal filter.

---

server/auvsi_suas/views/login.py
server/auvsi_suas/views/login_test.py

Return HTTP 401 on invalid creds.

---

server/auvsi_suas/models/mission_evaluation.py
server/auvsi_suas/models/mission_evaluation_test.py

Update to cubic obstacle scoring.

---

server/auvsi_suas/static/auvsi_suas/pages/evaluate-teams/evaluate-teams.html

Order evaluate teams list in UI by team username.

---

server/Dockerfile
server/config/configure_apache.sh

Add object img directory to volume path list.

---

server/auvsi_suas/models/fly_zone.py
server/auvsi_suas/models/mission_clock_event.py
server/auvsi_suas/models/mission_config.py
server/auvsi_suas/models/mission_judge_feedback.py
server/auvsi_suas/models/mission_judge_feedback_test.py
server/auvsi_suas/models/moving_obstacle.py
server/auvsi_suas/models/odlc.py
server/auvsi_suas/models/takeoff_or_landing_event.py

FlyZone simplified to not include boundary in display.
MissionConfig simplified to just contain ID, home, active.
MissionJudgeFeedback given a str- just ID, user, mission.
MovingObstacle simplified to not include waypoints.
Odlc simplified to not include most fields, user displayed with username.
For #271

Improve admin str representations for models.

---

server/auvsi_suas/models/mission_evaluation.py
server/auvsi_suas/models/mission_evaluation_test.py

Fix bug where server 500s when no objects present.

---

server/auvsi_suas/models/moving_obstacle_test.py
server/auvsi_suas/models/uas_telemetry.py
server/auvsi_suas/models/uas_telemetry_test.py

Handle dt=0 case for UasTelemetry waypoints.

---

server/auvsi_suas/models/odlc.py
server/auvsi_suas/models/odlc_test.py

Handle multiple orientations for alphanumerics.

---

client/Dockerfile
server/Dockerfile
server/auvsi_suas/models/distance_test.py
server/config/configure_postgresql.sh
server/config/postgresql.conf

Upgrade container base image to Ubuntu 18.04 LTS.

---

server/auvsi_suas/admin.py
server/auvsi_suas/models/access_log.py
server/auvsi_suas/models/access_log_test.py
server/auvsi_suas/models/aerial_position.py
server/auvsi_suas/models/aerial_position_test.py
server/auvsi_suas/models/fly_zone.py
server/auvsi_suas/models/fly_zone_test.py
server/auvsi_suas/models/gps_position.py
server/auvsi_suas/models/gps_position_test.py
server/auvsi_suas/models/mission_clock_event.py
server/auvsi_suas/models/mission_clock_event_test.py
server/auvsi_suas/models/mission_config.py
server/auvsi_suas/models/mission_config_test.py
server/auvsi_suas/models/mission_judge_feedback.py
server/auvsi_suas/models/mission_judge_feedback_test.py
server/auvsi_suas/models/moving_obstacle.py
server/auvsi_suas/models/moving_obstacle_test.py
server/auvsi_suas/models/odlc.py
server/auvsi_suas/models/odlc_test.py
server/auvsi_suas/models/stationary_obstacle.py
server/auvsi_suas/models/stationary_obstacle_test.py
server/auvsi_suas/models/takeoff_or_landing_event.py
server/auvsi_suas/models/takeoff_or_landing_event_test.py
server/auvsi_suas/models/time_period.py
server/auvsi_suas/models/uas_telemetry.py
server/auvsi_suas/models/uas_telemetry_test.py
server/auvsi_suas/models/waypoint.py
server/auvsi_suas/models/waypoint_test.py
server/auvsi_suas/views/obstacles_test.py
server/auvsi_suas/views/telemetry_test.py

Migrate to list_display for admin rather than str.

---

client/.gitignore
client/setup.py
client/test.sh
server/auvsi_suas/migrations/0034_remove_moving_obstacle.py
tools/setup_tools.sh

Fix setup.py script. Test install as part of CI.

---

client/auvsi_suas/client/client.py
client/auvsi_suas/client/types.py
client/auvsi_suas/client/types_test.py

Remove MovingObstacle from client types.

---

server/auvsi_suas/models/uas_telemetry.py
server/auvsi_suas/views/missions.py
server/auvsi_suas/views/telemetry.py

This will help determine which track is the active team, and help with
multi-mission scenarios. The icon is more intuitive than the track as
well.
For #311

Render live UAS position with icon and team name.

---

server/auvsi_suas/models/mission_config.py
server/auvsi_suas/models/mission_config_test.py

Use better icons to distinguish POIs.

---

server/auvsi_suas/models/fly_zone.py
server/auvsi_suas/models/mission_config.py
server/auvsi_suas/views/missions.py

Reorganize FlyZone KML under Mission folder.

---

server/auvsi_suas/models/mission_config.py

Add StationaryObstacle KML rendering.

---

server/auvsi_suas/models/access_log.py
server/auvsi_suas/models/aerial_position.py
server/auvsi_suas/models/fly_zone.py
server/auvsi_suas/models/gps_position.py
server/auvsi_suas/models/mission_config.py
server/auvsi_suas/models/mission_evaluation.py
server/auvsi_suas/models/mission_evaluation_test.py
server/auvsi_suas/models/mission_judge_feedback.py
server/auvsi_suas/models/odlc.py
server/auvsi_suas/models/stationary_obstacle.py
server/auvsi_suas/models/takeoff_or_landing_event.py
server/auvsi_suas/models/uas_telemetry.py
server/auvsi_suas/models/waypoint.py

 Update timeline scoring to reflect 2019 rules.

---

server/auvsi_suas/models/mission_evaluation.py
server/auvsi_suas/models/mission_evaluation_test.py

Update safety out of bounds penalty per 2019 rules.

---

server/auvsi_suas/models/odlc.py
server/auvsi_suas/models/odlc_test.py
server/auvsi_suas/models/pb_utils.py
server/auvsi_suas/models/pb_utils_test.py
server/auvsi_suas/views/odlcs.py
server/auvsi_suas/views/odlcs_test.py

Validates that the provided alphanumeric is either an upper case letter
or number.
Dedupes the enums for the database and proto.
For #349 
Fixes #387

Validate alphanumeric. Dedupe enums for Databse.

---

server/auvsi_suas/models/mission_evaluation.py

If the thumbnail_approved is None, then the ODLC has not been reviewed.
All ODLCs should be reviewed prior to scoring.
If the judge indicated the team flew for 3 minutes and achieved the
minimum autonomous flight time, there should be at least one flight
period.
Fixes #352

Warnings for unreviewed ODLC and missing takeoffs.

---

README.md

Move all documentation to README.

---

server/auvsi_suas/frontend/components/navigation.js
server/auvsi_suas/templates/mission.html
server/auvsi_suas/views/missions.py
server/auvsi_suas/views/missions_test.py
server/auvsi_suas/views/urls.py

Generates a printable webpage from the mission json string. Future
versions could improve the look with custom HTML.
For #315

Add simple page to print Mission Details.

---

server/auvsi_suas/models/access_log.py

Rather than loading all telemetry at once and generating O(N) time
durations for N telemetry points, compute the max/sum/count while
iterating. Reduces extra memory from O(N) to O(1).
For #430.

Use generator and reducer for rate calc.

---

client/configure.sh
client/interop-client.sh
server/interop-server.sh
tools/common.sh
tools/deploy.sh
tools/format.sh
tools/setup_tools.sh

Remove use of readlink for compatibility.

---

server/auvsi_suas/views/missions.py

Fix typo with lost comms position.

---

README.md

changed the README to reflect this

teams api returns an array not an object

---

client/.gitignore
client/Dockerfile
client/configure.sh
client/interop-client.sh
client/tools/interop_cli.py

Deprecate use of Python 2.7.

---

client/Dockerfile
server/Dockerfile
server/auvsi_suas/views/telemetry_test.py
server/config/requirements.txt

Upgrade to Ubuntu 20.04 LTS and simplekml 1.3.5.

---

server/auvsi_suas/models/mission_judge_feedback.py
server/auvsi_suas/models/test_utils.py
server/auvsi_suas/views/decorators.py
server/auvsi_suas/views/index_test.py
server/auvsi_suas/views/login_test.py
server/auvsi_suas/views/middleware.py
server/auvsi_suas/views/missions_test.py
server/auvsi_suas/views/odlcs_test.py
server/auvsi_suas/views/teams_test.py
server/auvsi_suas/views/telemetry_test.py
server/auvsi_suas/views/urls.py
server/auvsi_suas/views/utils_test.py
server/config/requirements.txt
server/docker-compose.yml
server/server/settings.py
server/server/urls.py

Upgrade to Django 2.2, Postgres 12.3.

---

client/requirements.txt

Upgrade pymavlink to 2.4.8.

---

.travis.yml

Upgrade Travis distro to xenial.

---

README.md
client/auvsi_suas/client/client.py
client/auvsi_suas/client/client_test.py
client/tools/interop_cli.py
client/tools/interop_cli_test.py

Add map image support in interop CLI.

---

README.md
server/auvsi_suas/models/mission_evaluation.py
server/auvsi_suas/models/mission_evaluation_test.py
server/auvsi_suas/models/test_utils.py

Adds map evaluation to the score report. Adds documentation for how to
review the uploaded maps as a judge in absence of a dedicated dashboard.
For #483.

Add evaluation of map uploads.

---

.github/workflows/cicd.yml
client/interop-client.sh
server/interop-server.sh
tools/setup_tools.sh

Add initial CI/CD via Actions with all but deploy.

---

.github/workflows/cicd.yml
server/docker-compose.yml

Refactor steps into jobs. Add healthcheck for DB.

---

.github/workflows/cicd.yml

Add fake use of secrets to test wiring & security.

---

.github/workflows/cicd.yml
.travis.yml
README.md

Note this is execpted to fail until the secret is updated to use a
proper access token.
For #474

Deploy via Actions rather than Travis.

---

.github/workflows/cicd.yml

Fix deploy job to first download & load image.

---

tools/deploy.sh

Push all tags when uploading docker image.

---

server/docker-compose.yml

Upgrades the version and switches to the minimal image.
For #499.

Switch to postgres 13.2-alpine.
